api:
  resource: ../src/
  type: attribute

api.v1.FixturePredictions:
  resource: ../src/FixturePredictions/Http/V1/
  type: attribute
  prefix: /v1

api.v1.User:
  resource: ../src/User/Http/V1/
  type: attribute
  prefix: /v1
