services:

  database:
    container_name: ${PROJECT_NAME}_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3309:${MYSQL_PORT}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./database/mysql:/var/lib/mysql
    env_file:
      - ./.env
      - ./.env.local

  webserver:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:stable-alpine
    ports:
      - 8010:8010
      - 8011:8011
    volumes:
      - ./backend:/var/www/html/backend
      - ./frontend:/var/www/html/frontend
      - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - php
      - database
    env_file:
      - ./.env
      - ./.env.local
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf" # Suffix is the same as file extension, to read the file like conf.

  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: ./php
    volumes:
      - ./backend:/var/www/html/backend
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - database
    env_file:
      - ./.env
      - ./.env.local

  node:
    container_name: ${PROJECT_NAME}_node
    image: node:latest
    working_dir: /var/www/html/frontend
    command: tail -f /dev/null
    ports:
      - 8012:5173
    volumes:
      - ./frontend:/var/www/html/frontend
    env_file:
      - ./.env
      - ./.env.local

  mailer:
    container_name: ${PROJECT_NAME}_mailer
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025