framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            default:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_DEFAULT)%'
                failure_transport: default_failed
            default_failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_DEFAULT_FAILED)%'
            fixture_predictions:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_FIXTURE_PREDICTIONS)%'
                failure_transport: fixture_predictions_failed
            fixture_predictions_failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_FIXTURE_PREDICTIONS_FAILED)%'
        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: default
            Symfony\Component\Notifier\Message\ChatMessage: default
            Symfony\Component\Notifier\Message\SmsMessage: default
when@test:
    framework:
        messenger:
            transports:
                default: 'sync://'
                fixture_predictions: 'sync://'