nelmio_api_doc:
    documentation:
        info:
            title: Project
            description: THERE IS NO TOMORROW!
            version: 1.0.0
        servers:
            - url: '%app.url%'
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            security:
                - Bearer: [ ]
    areas:
        path_patterns:
            - ^/auth
            - ^/users
            - ^/fixtures