nelmio_api_doc:
    documentation:
        info:
            title: '%app.name%'
            version: v1
        servers:
            - url: '%app.url%'
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas:
        path_patterns:
            - ^/v1