parameters:
    app.name: '%env(PROJECT_NAME)%'
    app.url: 'https://%env(DOMAIN_API)%'
    app.support.email: '%env(APP_SUPPORT_EMAIL)%'
    app.mail.domain: '%env(APP_MAIL_DOMAIN)%'
    client.url: 'https://%env(DOMAIN)%'
    client.url.auth-verification-success: 'https://%env(DOMAIN)%/auth-forms/sign-in?verify=success'
    client.url.auth-verification-fail: 'https://%env(DOMAIN)%/auth-forms/sign-in?verify=fail'
    auth.sign.up.code: '%env(SIGN_UP_CODE)%'
    fixtures.football-data-org.api.url: '%env(FOOTBALL_DATA_ORG_URL)%'
    fixtures.football-data-org.api.key: '%env(FOOTBALL_DATA_ORG_KEY)%'