security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        public:
            pattern:
                - ^/auth
            security: false
        secured:
            lazy: true
            json_login:
                check_path: sign_in
                username_path: email
                password_path: password
            access_token:
                token_handler: App\Security\AccessTokenHandler
#            login_link:
#                check_route: sign_in_check_link
#                signature_properties: ['id', 'email']
#                max_uses: 3 # https://symfony.com/doc/current/security/login_link.html#allow-a-link-to-only-be-used-once
#                lifetime: 300 # seconds
    access_control:
#        - { path: ^/test, roles: ROLE_USER }
        - { path: ^/auth, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
