when@prod:
  sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
      # see https://docs.sentry.io/platforms/php/data-management/data-collected
      send_default_pii: true
      enable_logs: true
      ignore_exceptions:
        - 'Symfony\Component\Debug\Exception\FatalErrorException'
        - 'Symfony\Component\ErrorHandler\Error\FatalError'
        - 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException'
        - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
        - 'Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException'
        - 'Symfony\Component\Security\Core\Exception\AccessDeniedException'

  monolog:
    # see https://docs.sentry.io/platforms/php/guides/symfony/integrations/monolog/
    handlers:
      sentry_breadcrumbs:
        type: service
        name: sentry_breadcrumbs
        id: Sentry\Monolog\BreadcrumbHandler
      sentry_logs:
        type: service
        id: Sentry\SentryBundle\Monolog\LogsHandler

  services:
    Sentry\Monolog\BreadcrumbHandler:
      arguments:
        - '@Sentry\State\HubInterface'
        - !php/const Monolog\Level::Warning
    Sentry\SentryBundle\Monolog\LogsHandler:
      arguments:
        - !php/const Monolog\Level::Warning