services:

  database:
    container_name: ${PROJECT_NAME}_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./database/mysql:/var/lib/mysql
    env_file: [ ./.env, ./.env.prod, ./.env.local ]

  webserver:
    container_name: ${PROJECT_NAME}_nginx
    build:
      context: ./nginx/prod
    ports:
      - ${APP_PORT}:80
      - ${APP_PORT_HTTPS}:443
    volumes:
      - ../backend:/var/www/html/backend
      - ../frontend:/var/www/html/frontend
      - ./nginx/prod/cron.d:/etc/cron.d
      - ./nginx/prod/letsencrypt:/etc/letsencrypt
      - ./nginx/prod/templates:/etc/nginx/templates
      - ./nginx/prod/entrypoint.sh:/entrypoint.sh
      - ./nginx/prod/renew-certificates.sh:/renew-certificates.sh
    depends_on: [ php ]
    env_file: [ ./.env, ./.env.prod, ./.env.local ]
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf" # Set to file extension, to keep it instead of ".template".
    entrypoint: [ "/entrypoint.sh" ]
    command: [ "nginx", "-g", "daemon off;" ]

  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: ./php
      target: php
    volumes:
      - ../backend:/var/www/html/backend
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on: [ database ]
    env_file: [ ./.env, ./.env.prod, ./.env.local ]

  php_supervisor:
    container_name: ${PROJECT_NAME}_php_supervisor
    build:
      context: ./php
      target: php_supervisor
    command: supervisord -c /etc/supervisor/supervisord.conf -n
    volumes:
      - ../backend:/var/www/html/backend
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/supervisor:/etc/supervisor/conf.d
    depends_on: [ database ]
    env_file: [ ./.env, ./.env.prod, ./.env.local ]

  node:
    container_name: ${PROJECT_NAME}_node
    image: node:latest
    working_dir: /var/www/html/frontend
    volumes:
      - ../frontend:/var/www/html/frontend
    env_file: [ ./.env, ./.env.prod, ./.env.local ]
    command: tail -f /dev/null