services:

  database:
    container_name: ${PROJECT_NAME}_database
    image: mysql:8.0
    ports:
      - ${DATABASE_PORT}:${MYSQL_PORT}
    volumes:
      - ./common/database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./common/database/mysql:/var/lib/mysql
    env_file: [ ./.env, ./.env.prod, ./.env.local ]
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 10

  webserver:
    container_name: ${PROJECT_NAME}_nginx
    build:
      context: ./prod/nginx
    ports:
      - ${APP_PORT}:80
      - ${APP_PORT_HTTPS}:443
    volumes:
      - ../backend:/var/www/html/backend
      - ../frontend:/var/www/html/frontend
      - ./prod/nginx/cron.d:/etc/cron.d
      - ./prod/nginx/letsencrypt:/etc/letsencrypt
      - ./prod/nginx/templates:/etc/nginx/templates
      - ./prod/nginx/entrypoint.sh:/entrypoint.sh
      - ./prod/nginx/renew-certificates.sh:/renew-certificates.sh
    depends_on:
      database:
        condition: service_healthy
    env_file: [ ./.env, ./.env.prod, ./.env.local ]
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf" # Set to file extension, to keep it instead of ".template".
    entrypoint: [ "/entrypoint.sh" ]
    command: [ "nginx", "-g", "daemon off;" ]

  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: ./common/php
      target: php
    volumes:
      - ../backend:/var/www/html/backend
      - ./common/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      database:
        condition: service_healthy
    env_file: [ ./.env, ./.env.prod, ./.env.local ]

  php_supervisor:
    container_name: ${PROJECT_NAME}_php_supervisor
    build:
      context: ./common/php
      target: php_supervisor
    command: supervisord -c /etc/supervisor/supervisord.conf -n
    volumes:
      - ../backend:/var/www/html/backend
      - ./common/php/php.ini:/usr/local/etc/php/php.ini
      - ./common/php/supervisor:/etc/supervisor/conf.d
    depends_on: [ database ]
    env_file: [ ./.env, ./.env.prod, ./.env.local ]

  node:
    container_name: ${PROJECT_NAME}_node
    image: node:latest
    working_dir: /var/www/html/frontend
    volumes:
      - ../frontend:/var/www/html/frontend
    env_file: [ ./.env, ./.env.prod, ./.env.local ]
    command: tail -f /dev/null